name: artifact

on: [push]

env:
  FILE_NAME: hello-artifact

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}
