name: test the script

on: [push]

env:
  FILE_NAME: hello-artifact

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Setup Python environment
      run: python hello.py
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: .