name: artifact

on: [push]

env:
  FILE_NAME: hello-artifact

jobs:
  jobs:
    test:
  
      runs-on: ubuntu-latest
  
      steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
      - name: Install requirements
        run: pip install --quiet --requirement requirements.txt
      - name: Python Syntax Checker
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 --disable-C0326 *.py
      - name: Run unit tests
        run: |
          python -m unittest --verbose --failfast
  
    build:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
      - name: Check out the code
        uses: actions/checkout@v2  
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: .